// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.7

package handler

import (
	"net/http"

	"dcloud/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 程序升级历史查询
				Method:  http.MethodPost,
				Path:    "/api/v1/ota/app-update-history",
				Handler: OtaHistoryQueryHandler(serverCtx),
			},
			{
				// 查询程序应用的版本信息
				Method:  http.MethodPost,
				Path:    "/api/v1/ota/app-version-query",
				Handler: OtaVersionQueryHandler(serverCtx),
			},
			{
				// 手动触发升级
				Method:  http.MethodPost,
				Path:    "/api/v1/ota/manual-upgrade",
				Handler: OtaManualUpgradeHandler(serverCtx),
			},
			{
				// 上报升级结果
				Method:  http.MethodPost,
				Path:    "/api/v1/ota/receipt",
				Handler: OtaReceiptHandler(serverCtx),
			},
			{
				// 查询机器人基础信息
				Method:  http.MethodPost,
				Path:    "/api/v1/ota/robot-query",
				Handler: OtaRobotQueryHandler(serverCtx),
			},
			{
				// 查询机器人程序版本信息
				Method:  http.MethodPost,
				Path:    "/api/v1/ota/robot-version-query",
				Handler: OtaRobotVersionQueryHandler(serverCtx),
			},
			{
				// 回滚请求
				Method:  http.MethodPost,
				Path:    "/api/v1/ota/rollback",
				Handler: OtaRollbackHandler(serverCtx),
			},
			{
				// 升级应用程序
				Method:  http.MethodPost,
				Path:    "/api/v1/ota/upgrade",
				Handler: OtaUpgradeHandler(serverCtx),
			},
		},
	)
}
