// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.7

package types

type AppVersionInfo struct {
	AppName     string `json:"app_name"`     // 应用名称
	PkgName     string `json:"pkg_name"`     // 程序包名称
	Version     string `json:"version"`      // 版本号
	VersionDesc string `json:"version_desc"` // 版本描述
	Operator    string `json:"operator"`     // 操作用户
	CreateTime  string `json:"create_time"`  // 创建时间
}

type AppVersionQryRequest struct {
	AppName string `json:"app_name"` // 应用名称
	Page    int    `json:"page"`     // 页码
	Limit   int    `json:"limit"`    // 每页数量
}

type AppVersionQryResponse struct {
	Code    int              `json:"code"`    // 状态码
	Message string           `json:"message"` // 状态信息
	Total   int              `json:"total"`   // 总记录数
	List    []AppVersionInfo `json:"list"`    // 版本信息列表
}

type ManualUpgradeRequest struct {
	RobotSn  string `json:"robot_sn"` // 机器人序列号
	AppName  string `json:"app_name"` // 应用名称
	Version  string `json:"version"`  // 版本号
	Operator string `json:"operator"` // 操作用户
}

type ManualUpgradeResponse struct {
	Code    int    `json:"code"`    // 状态码
	Message string `json:"message"` // 状态信息
	Result  int    `json:"result"`  // 升级结果   1-升级成功 2-升级失败 3－回滚成功 4-回滚失败
}

type ReceiptRequest struct {
	RobotSn string `json:"robot_sn"` // 机器人序列号
	AppName string `json:"app_name"` // 应用名称
	Result  int    `json:"result"`   // 升级结果   1-升级成功 2-升级失败 3－回滚成功 4-回滚失败
	Message string `json:"message"`  // 结果信息
}

type ReceiptResponse struct {
	Code    int    `json:"code"`    // 状态码
	Message string `json:"message"` // 状态信息
}

type RobotInfo struct {
	RobotSn         string `json:"robot_sn"`         // 机器人序列号
	RobotName       string `json:"robot_name"`       // 机器人名称
	RobotType       int    `json:"robot_type"`       // 机器人类型
	FirmwareVersion string `json:"firmware_version"` // 固件版本
	Region          string `json:"region"`           // 区域
	RobotIp         string `json:"robot_ip"`         // 机器人IP地址
	RobotPort       int    `json:"robot_port"`       // 机器人端口号
	Address         string `json:"address"`          // 地址
	BatteryLevel    string `json:"battery_level"`    // 电池电量
	CurVersion      string `json:"cur_version"`      // 当前版本号
	RobotStatus     int    `json:"robot_status"`     // 机器人状态
	ErrLogs         string `json:"err_logs"`         // 错误日志
	Operator        string `json:"operator"`         // 操作用户
}

type RobotQryRequest struct {
	RobotSn string `json:"robot_sn,optional"` // 机器人序列号
	Page    int    `json:"page"`              // 页码
	Limit   int    `json:"limit"`             // 每页数量
}

type RobotQryResponse struct {
	Code    int         `json:"code"`    // 状态码
	Message string      `json:"message"` // 状态信息
	List    []RobotInfo `json:"list"`    // 机器人信息列表
}

type RobotVersionInfo struct {
	Id              int64  `json:"id"`                // 记录ID
	RobotSn         string `json:"robot_sn"`          // 机器人序列号
	AppName         string `json:"app_name"`          // 应用名称
	AppType         int    `json:"app_type"`          // 应用类型
	Version         string `json:"version"`           // 版本号
	VersionDesc     string `json:"version_desc"`      // 版本描述
	FilePath        string `json:"file_path"`         // 程序文件路径
	UpdateStatus    int    `json:"update_status"`     // 更新状态 1-待升级 2-升级中 3-升级完成 4-升级失败 5-回滚中 6-回滚完成 7-回滚失败
	UpdateLogs      string `json:"update_logs"`       // 更新日志
	UpdateStartTime string `json:"update_start_time"` // 更新开始时间
	UpdateEndTime   string `json:"update_end_time"`   // 更新结束时间
	Operator        string `json:"operator"`          // 操作用户
}

type RobotVersionQryRequest struct {
	RobotSn   string `json:"robot_sn"`   // 机器人序列号
	AppName   string `json:"app_name"`   // 应用名称
	QueryType int    `json:"query_type"` // 查询类型 1-本地; 2 - 同步远程
	Page      int    `json:"page"`       // 页码
	Limit     int    `json:"limit"`      // 每页数量
}

type RobotVersionQryResponse struct {
	Code    int                `json:"code"`    // 状态码
	Message string             `json:"message"` // 状态信息
	List    []RobotVersionInfo `json:"list"`    // 版本信息列表
}

type RollbackRequest struct {
	AppName         string `json:"app_name"`         // 应用名称
	RollbackType    int    `json:"rollback_type"`    // 回滚类型 1-全量回滚 2-增量回滚
	RobotSn         string `json:"robot_sn"`         // 机器人序列号
	CurVersion      string `json:"cur_version"`      // 当前版本号
	RollbackVersion string `json:"rollback_version"` // 回滚版本号
	Operator        string `json:"operator"`         // 操作用户
}

type RollbackResponse struct {
	Code    int    `json:"code"`    // 状态码
	Message string `json:"message"` // 状态信息
	Result  int    `json:"result"`  // 回滚结果   1-回滚成功 2-回滚失败
}

type UpgradeHistoryInfo struct {
	Id          int    `json:"id"`           // 记录ID
	RobotSn     string `json:"robot_sn"`     // 机器人序列号
	AppName     string `json:"app_name"`     // 应用名称
	Version     string `json:"version"`      // 版本号
	OperType    int    `json:"oper_type"`    // 操作类型 1-升级 2-回滚
	Operator    string `json:"operator"`     // 操作用户
	UpgradeTime string `json:"upgrade_time"` // 升级时间
}

type UpgradeHistoryQryRequest struct {
	RobotSn string `json:"robot_sn"` // 机器人序列号
	AppName string `json:"app_name"` // 应用名称
	Page    int    `json:"page"`     // 页码
	Limit   int    `json:"limit"`    // 每页数量
}

type UpgradeHistoryQryResponse struct {
	Code    int                  `json:"code"`    // 状态码
	Message string               `json:"message"` // 状态信息
	List    []UpgradeHistoryInfo `json:"list"`    // 升级历史信息列表
}

type UpgradeRequest struct {
	AppName       string `json:"app_name"`       // 应用名称
	FileUrl       string `json:"file_url"`       // 应用程序地址
	VersionType   int    `json:"version_type"`   // 更新版本号类型1—主版本号 2—次版本号 3—修订号
	UpdateContent string `json:"update_content"` // 更新内容
	Operator      string `json:"operator"`       // 操作用户
}

type UpgradeResponse struct {
	Code    int    `json:"code"`    // 状态码
	Message string `json:"message"` // 状态信息
}
